// frontend/src/pages/PrivacyPolicyPage.js
import React from 'react';
import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';

const PrivacyPolicyPage = () => {
    const YOUR_APP_NAME = "EchoWrite";
    const YOUR_COMPANY_NAME_OR_YOUR_NAME = "EchoWrite"; // Replace
    const YOUR_CONTACT_EMAIL = "adnanhaider4878@gmail.com"; // Replace
    const EFFECTIVE_DATE = "May 17, 2025"; // Replace

    return (
        <>
            <Helmet>
                <title>{YOUR_APP_NAME} - Privacy Policy</title>
                <meta name="description" content={`Privacy Policy for ${YOUR_APP_NAME}.`} />
            </Helmet>
            <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12 dark:text-slate-200">
                <h1 className="text-3xl font-bold text-gray-900 dark:text-slate-100 mb-6">Privacy Policy</h1>
                <p className="text-sm text-gray-500 dark:text-slate-400 mb-6">Effective Date: {EFFECTIVE_DATE}</p>

                <p className="mb-4">This Privacy Policy describes how {YOUR_COMPANY_NAME_OR_YOUR_NAME} ("we," "us," or "our") collects, uses, and shares information about you when you use our {YOUR_APP_NAME} Service.</p>

                <h2 className="text-2xl font-semibold text-gray-800 dark:text-slate-200 mt-6 mb-3">1. Information We Collect</h2>
                <p className="mb-2">We may collect the following types of information:</p>
                <ul className="list-disc list-inside mb-4 space-y-1 pl-4">
                    <li><strong>Account Information:</strong> When you register, we collect your username, email address, and hashed password. If you sign up with Google OAuth, we receive your name, email, and profile identifier from Google.</li>
                    <li><strong>User Content:</strong> We store the content you input for repurposing (e.g., blog posts, scripts) and the snippets generated by you or the AI.</li>
                    <li><strong>User-Defined Data:</strong> This includes folders, snippet templates, and audience personas you create.</li>
                    <li><strong>API Keys (BYOK):</strong> If you use the "Bring Your Own Key" feature for third-party AI services (OpenAI, Gemini, Perplexity AI), we store these keys. They are encrypted at rest in our database. We only use them to make API calls to the respective services on your behalf as you initiate actions within the app.</li>
                    <li><strong>Payment Information:</strong> We do not directly collect or store your credit card details. All payments are processed by our third-party payment processor, Paddle.com (our Merchant of Record). Paddle may collect payment information directly from you subject to their privacy policy. We may receive transaction identifiers and subscription status from Paddle.</li>
                    <li><strong>Usage Data:</strong> We collect information about how you use the Service, such as features accessed, actions taken, and error logs (e.g., via Google Analytics). This helps us improve the Service.</li>
                    <li><strong>Cookies and Similar Technologies:</strong> We use cookies (e.g., for session management) and similar technologies.</li>
                </ul>

                <h2 className="text-2xl font-semibold text-gray-800 dark:text-slate-200 mt-6 mb-3">2. How We Use Your Information</h2>
                <p className="mb-2">We use your information to:</p>
                <ul className="list-disc list-inside mb-4 space-y-1 pl-4">
                    <li>Provide, maintain, and improve the Service.</li>
                    <li>Process your registration and manage your account.</li>
                    <li>Process subscriptions and payments (via Paddle).</li>
                    <li>Communicate with you, including sending service-related emails.</li>
                    <li>Facilitate your use of third-party AI services when you provide API keys.</li>
                    <li>Personalize your experience.</li>
                    <li>Analyze usage to understand how our Service is used.</li>
                </ul>

                <h2 className="text-2xl font-semibold text-gray-800 dark:text-slate-200 mt-6 mb-3">3. How We Share Your Information</h2>
                <p className="mb-2">We do not sell your personal information. We may share information as follows:</p>
                <ul className="list-disc list-inside mb-4 space-y-1 pl-4">
                    <li><strong>With Third-Party AI Providers (BYOK):</strong> When you use your API keys, your User Content is sent to the respective AI provider (OpenAI, Google, Perplexity) for processing according to their terms and privacy policies. We do not control their data handling.</li>
                    <li><strong>With Payment Processors:</strong> We share necessary information with Paddle.com to process your payments.</li>
                    <li><strong>With Service Providers:</strong> We may use third-party companies for hosting, analytics (e.g., Google Analytics), and customer support, who may access your information only to perform tasks on our behalf.</li>
                    <li><strong>For Legal Reasons:</strong> If required by law or in response to valid legal requests.</li>
                    <li><strong>Business Transfers:</strong> In connection with a merger, acquisition, or sale of assets.</li>
                </ul>
                <p className="mb-4">Shared community templates will display your username as the creator but not your email or other private account information.</p>


                <h2 className="text-2xl font-semibold text-gray-800 dark:text-slate-200 mt-6 mb-3">4. Data Security</h2>
                <p className="mb-4">We take reasonable measures to protect your information, including encrypting sensitive data like API keys and passwords. However, no internet transmission is 100% secure.</p>

                <h2 className="text-2xl font-semibold text-gray-800 dark:text-slate-200 mt-6 mb-3">5. Data Retention</h2>
                <p className="mb-4">We retain your personal information for as long as your account is active or as needed to provide you with the Service, comply with our legal obligations, resolve disputes, and enforce our agreements.</p>

                <h2 className="text-2xl font-semibold text-gray-800 dark:text-slate-200 mt-6 mb-3">6. Your Choices and Rights</h2>
                <p className="mb-4">You can access and update your account information through your profile settings. You may also have other rights depending on your jurisdiction (e.g., data deletion, access under GDPR/CCPA). Please contact us for such requests.</p>

                <h2 className="text-2xl font-semibold text-gray-800 dark:text-slate-200 mt-6 mb-3">7. Children's Privacy</h2>
                <p className="mb-4">Our Service is not intended for children under the age of 13 (or a higher age if stipulated by local law). We do not knowingly collect personal information from children.</p>

                <h2 className="text-2xl font-semibold text-gray-800 dark:text-slate-200 mt-6 mb-3">8. Changes to This Policy</h2>
                <p className="mb-4">We may update this Privacy Policy. We will notify you of significant changes by posting the new policy on our site and updating the effective date.</p>

                <h2 className="text-2xl font-semibold text-gray-800 dark:text-slate-200 mt-6 mb-3">9. Contact Us</h2>
                <p className="mb-4">If you have any questions about this Privacy Policy, please contact us at <a href={`mailto:${YOUR_CONTACT_EMAIL}`} className="text-indigo-600 dark:text-indigo-400 hover:underline">{YOUR_CONTACT_EMAIL}</a>.</p>
            </div>
        </>
    );
};

export default PrivacyPolicyPage;