// frontend/src/pages/TermsOfServicePage.js
import React from 'react';
import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom'; // If you need to link to other pages like Privacy Policy

const TermsOfServicePage = () => {
    const YOUR_APP_NAME = "EchoWrite";
    const YOUR_COMPANY_NAME_OR_YOUR_NAME = "EchoWrite"; // Replace
    const YOUR_CONTACT_EMAIL = "adnanhaider4878@gmail.com"; // Replace
    const EFFECTIVE_DATE = "May 17, 2025"; // Replace with actual date

    return (
        <>
            <Helmet>
                <title>{YOUR_APP_NAME} - Terms of Service</title>
                <meta name="description" content={`Terms of Service for ${YOUR_APP_NAME}.`} />
            </Helmet>
            <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12 dark:text-slate-200">
                <h1 className="text-3xl font-bold text-gray-900 dark:text-slate-100 mb-6">Terms of Service</h1>
                <p className="text-sm text-gray-500 dark:text-slate-400 mb-6">Effective Date: {EFFECTIVE_DATE}</p>

                <p className="mb-4">Welcome to {YOUR_APP_NAME}! These Terms of Service ("Terms") govern your use of our website, applications, and services (collectively, the "Service") provided by {YOUR_COMPANY_NAME_OR_YOUR_NAME} ("we," "us," or "our"). By accessing or using our Service, you agree to be bound by these Terms. If you do not agree to these Terms, please do not use our Service.</p>

                <h2 className="text-2xl font-semibold text-gray-800 dark:text-slate-200 mt-6 mb-3">1. Account Registration</h2>
                <p className="mb-4">To use certain features of the Service, you may be required to create an account. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete. You are responsible for safeguarding your password and for all activities that occur under your account.</p>

                <h2 className="text-2xl font-semibold text-gray-800 dark:text-slate-200 mt-6 mb-3">2. Use of Service</h2>
                <p className="mb-2">You agree to use the Service only for lawful purposes and in accordance with these Terms. You are responsible for all content you input into the Service ("User Content") and any content generated by the AI based on your input.</p>
                <ul className="list-disc list-inside mb-4 space-y-1 pl-4">
                    <li>You retain ownership of your original User Content.</li>
                    <li>Content generated by the AI tools based on your input is for your use, subject to the terms of any third-party AI providers if you use the "Bring Your Own Key" (BYOK) feature.</li>
                    <li>You agree not to use the Service to generate content that is illegal, harmful, infringing, defamatory, or otherwise objectionable.</li>
                </ul>

                <h2 className="text-2xl font-semibold text-gray-800 dark:text-slate-200 mt-6 mb-3">3. AI Services and BYOK</h2>
                <p className="mb-4">{YOUR_APP_NAME} integrates with third-party AI services (e.g., OpenAI, Google Gemini, Perplexity AI). You may choose to use these services by providing your own API keys ("Bring Your Own Key" or BYOK). When using BYOK:</p>
                <ul className="list-disc list-inside mb-4 space-y-1 pl-4">
                    <li>You are responsible for your usage of these third-party AI services and any associated costs incurred with those providers.</li>
                    <li>Your use of third-party AI services is subject to their respective terms of service and privacy policies.</li>
                    <li>{YOUR_APP_NAME} acts as a facilitator and is not responsible for the output, accuracy, or availability of these third-party AI services. We securely handle your API keys as described in our <Link to="/privacy-policy" className="text-indigo-600 dark:text-indigo-400 hover:underline">Privacy Policy</Link>.</li>
                </ul>
                {/* Add a section if you offer managed AI credits/tiers */}

                <h2 className="text-2xl font-semibold text-gray-800 dark:text-slate-200 mt-6 mb-3">4. Subscription and Payments</h2>
                <p className="mb-4">Certain features of the Service may require a paid subscription. All payments are processed through our third-party payment processor, Paddle.com (our Merchant of Record). By subscribing, you agree to Paddle's terms and our payment terms. Subscription fees are [non-refundable, or specify your refund policy, linking to it].</p>
                {/* Detail your subscription model, renewal, cancellation here or link to a separate policy */}

                <h2 className="text-2xl font-semibold text-gray-800 dark:text-slate-200 mt-6 mb-3">5. User-Defined Templates & Community Sharing</h2>
                <p className="mb-4">You may create and use snippet templates. If you choose to share your templates with the {YOUR_APP_NAME} community:</p>
                <ul className="list-disc list-inside mb-4 space-y-1 pl-4">
                    <li>You grant {YOUR_APP_NAME} a non-exclusive, worldwide, royalty-free license to display, distribute, and allow other users to use and clone your shared templates within the Service.</li>
                    <li>You represent that your shared templates do not infringe on any third-party rights.</li>
                    <li>We reserve the right to remove any shared template for any reason.</li>
                </ul>


                <h2 className="text-2xl font-semibold text-gray-800 dark:text-slate-200 mt-6 mb-3">6. Intellectual Property</h2>
                <p className="mb-4">The Service and its original content (excluding User Content and AI-generated content based on user input), features, and functionality are and will remain the exclusive property of {YOUR_COMPANY_NAME_OR_YOUR_NAME} and its licensors.</p>

                <h2 className="text-2xl font-semibold text-gray-800 dark:text-slate-200 mt-6 mb-3">7. Termination</h2>
                <p className="mb-4">We may terminate or suspend your account and access to the Service immediately, without prior notice or liability, for any reason whatsoever, including, without limitation, if you breach these Terms.</p>

                <h2 className="text-2xl font-semibold text-gray-800 dark:text-slate-200 mt-6 mb-3">8. Disclaimer of Warranties; Limitation of Liability</h2>
                <p className="mb-4">The Service is provided "AS IS" and "AS AVAILABLE" without warranties of any kind. We do not warrant that the Service will be error-free or uninterrupted. In no event shall {YOUR_COMPANY_NAME_OR_YOUR_NAME} be liable for any indirect, incidental, special, consequential, or punitive damages...</p>
                {/* THIS SECTION IS VERY IMPORTANT AND NEEDS LEGAL REVIEW */}

                <h2 className="text-2xl font-semibold text-gray-800 dark:text-slate-200 mt-6 mb-3">9. Governing Law</h2>
                <p className="mb-4">These Terms shall be governed by the laws of [Your Jurisdiction - e.g., your country, or state/country if incorporated], without regard to its conflict of law provisions.</p>

                <h2 className="text-2xl font-semibold text-gray-800 dark:text-slate-200 mt-6 mb-3">10. Changes to Terms</h2>
                <p className="mb-4">We reserve the right to modify these Terms at any time. We will provide notice of material changes. By continuing to use the Service after changes become effective, you agree to be bound by the revised Terms.</p>

                <h2 className="text-2xl font-semibold text-gray-800 dark:text-slate-200 mt-6 mb-3">11. Contact Us</h2>
                <p className="mb-4">If you have any questions about these Terms, please contact us at <a href={`mailto:${YOUR_CONTACT_EMAIL}`} className="text-indigo-600 dark:text-indigo-400 hover:underline">{YOUR_CONTACT_EMAIL}</a>.</p>
            </div>
        </>
    );
};

export default TermsOfServicePage;