# Stage 1: Build React App
FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Stage 2: Serve using nginx
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html  
# COPY --from=build /app/build /usr/share/nginx/html  # for CRA

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]